FROM docker.io/archlinux:latest

RUN pacman -Syu --noconfirm git make cmake clang ninja unzip
RUN git clone --depth=1 https://github.com/neovim/neovim.git home/neovim

WORKDIR home/neovim
RUN make deps
RUN make
RUN make install
